/**
 * @desc    Generate playlist based on mood/activity
 * @route   POST /api/mood-generator/generate
 * @access  Protected
 */
export const generateMoodPlaylist = async (req, res) => {
  const { mood, activity, description, limit = 30 } = req.body;

  if (!mood && !activity && !description) {
    return res.status(400).json({ 
      message: 'Please provide mood, activity, or description' 
    });
  }

  try {
    // Call ML API for smart generation
    const response = await axios.post(`${ML_API_URL}/generate/mood-playlist`, {
      mood,
      activity,
      description,
      limit,
      user_id: req.user._id.toString(),
    }, {
      timeout: 30000
    });

    res.json({
      tracks: response.data.tracks,
      playlistName: response.data.playlistName,
      description: response.data.description,
      moodProfile: response.data.moodProfile,
    });

  } catch (err) {
    console.error('Error generating mood playlist:', err.message);
    
    // Fallback: Use Spotify recommendations
    if (err.code === 'ECONNREFUSED' || err.code === 'ETIMEDOUT') {
      return fallbackMoodGeneration(req, res, mood, activity, limit);
    }
    
    if (err.response) {
      return res.status(err.response.status).json({ 
        message: 'ML API error: ' + (err.response.data?.message || err.message) 
      });
    }
    
    res.status(500).json({ message: 'Failed to generate mood playlist' });
  }
};

async function fallbackMoodGeneration(req, res, mood, activity, limit) {
  try {
    const spotifyApi = new SpotifyWebApi();
    spotifyApi.setAccessToken(req.user.accessToken);

    // Get user's top tracks as seeds
    const topTracks = await spotifyApi.getMyTopTracks({ limit: 5, time_range: 'short_term' });
    const seedTracks = topTracks.body.items.slice(0, 3).map(t => t.id);

    // Mood to audio features mapping
    const moodFeatures = getMoodFeatures(mood, activity);

    // Get recommendations
    const recommendations = await spotifyApi.getRecommendations({
      seed_tracks: seedTracks,
      limit: limit,
      ...moodFeatures
    });

    res.json({
      tracks: recommendations.body.tracks,
      playlistName: `${mood || activity} Mix`,
      description: `Generated for ${mood || activity}`,
      source: 'fallback',
      message: 'Using Spotify recommendations (ML service unavailable)'
    });

  } catch (err) {
    console.error('Fallback generation failed:', err.message);
    res.status(500).json({ message: 'Failed to generate playlist' });
  }
}

function getMoodFeatures(mood, activity) {
  const features = {};
  
  const moodLower = (mood || activity || '').toLowerCase();
  
  if (moodLower.includes('happy') || moodLower.includes('joyful')) {
    features.target_valence = 0.8;
    features.target_energy = 0.7;
  } else if (moodLower.includes('sad') || moodLower.includes('melancholy')) {
    features.target_valence = 0.2;
    features.target_energy = 0.3;
  } else if (moodLower.includes('energetic') || moodLower.includes('workout')) {
    features.target_valence = 0.7;
    features.target_energy = 0.9;
  } else if (moodLower.includes('calm') || moodLower.includes('relax')) {
    features.target_valence = 0.5;
    features.target_energy = 0.3;
  } else if (moodLower.includes('focus') || moodLower.includes('study')) {
    features.target_valence = 0.5;
    features.target_energy = 0.5;
    features.target_instrumentalness = 0.7;
  }
  
  return features;
}

/**
 * @desc    Create and save generated playlist to Spotify
 * @route   POST /api/mood-generator/save
 * @access  Protected
 */
export const saveMoodPlaylist = async (req, res) => {
  const { name, trackUris, description, isPublic = true } = req.body;

  if (!name || !trackUris || !Array.isArray(trackUris)) {
    return res.status(400).json({ 
      message: 'Playlist name and track URIs are required' 
    });
  }

  try {
    const spotifyApi = new SpotifyWebApi();
    spotifyApi.setAccessToken(req.user.accessToken);
    
    // Create playlist
    const playlist = await spotifyApi.createPlaylist(name, {
      description: description || 'Generated by MoodiQ-AI',
      public: isPublic,
    });

    // Add tracks in batches
    const batches = [];
    for (let i = 0; i < trackUris.length; i += 100) {
      batches.push(trackUris.slice(i, i + 100));
    }

    for (const batch of batches) {
      await spotifyApi.addTracksToPlaylist(playlist.body.id, batch);
    }

    res.json({
      success: true,
      playlistId: playlist.body.id,
      playlistUrl: playlist.body.external_urls.spotify,
      tracksAdded: trackUris.length,
    });

  } catch (err) {
    console.error('Error saving mood playlist:', err.message);
    res.status(500).json({ message: 'Failed to save playlist' });
  }
};
